name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Restore CI Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build
        run: yarn build

      - name: Publish to Build Branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Publishing to build branch..."
          set -e # Exit with nonzero exit code if anything fails

          # Set up variables

          GITHUB_ACTOR=${{ github.actor }}
          GITHUB_REPO=${{ github.repository }}
          GITHUB_SHA=${{ github.sha }}
          GITHUB_REF=${{ github.ref }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GITHUB_EMAIL="anish.shobith19@gmail.com"
          BUILD_BRANCH="build"

          # Checkout the repo to the previous commit
          git checkout ${GITHUB_SHA}^1

          # Create a new branch that will contain only the build files
          git checkout -b ${BUILD_BRANCH}

          # Delete all files except the build files
          find . -not -path "./dist/*" -not -name ".git" -delete

          # Move the build files to the root directory
          mv dist/* . && rm -rf dist

          # Push the new branch
          git config --global user.email ${GITHUB_EMAIL}
          git config --global user.name ${GITHUB_ACTOR}
          git add -fA
          git commit --allow-empty -m "Build ${GITHUB_SHA}"

          # Force push to the build branch
          git push -f origin ${BUILD_BRANCH}

          # Go back to the original branch
          git checkout ${GITHUB_REF}

          echo "Published to build branch!"

          

